# Generated by Django 2.2.4 on 2021-05-03 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handyhelper_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='maked_by',
            new_name='posted_by',
        ),
    ]
