# Generated by Django 2.2.4 on 2021-05-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handyhelper_app', '0002_auto_20210503_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='add_job',
            field=models.ManyToManyField(related_name='add_jobs', to='handyhelper_app.User'),
        ),
        migrations.AddField(
            model_name='job',
            name='give_up',
            field=models.BooleanField(default=False),
        ),
    ]
