# Generated by Django 2.2.4 on 2021-05-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handyhelper_app', '0003_auto_20210503_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='give_up',
            field=models.BooleanField(default=True),
        ),
    ]
